usr/include/* usr/include/
#usr/include/*/* usr/include/
usr/lib/*/lib*.so usr/lib/${DEB_HOST_MULTIARCH}/
usr/lib/*/cmake usr/lib/${DEB_HOST_MULTIARCH}/
#usr/share/mimalloc-2.0/cmake/*
#./cmake/mimalloc-config-version.cmake
#./cmake/mimalloc-config.cmake
#./debian/tmp/usr/lib/x86_64-linux-gnu/cmake/mimalloc-2.0/mimalloc.cmake
#./debian/tmp/usr/lib/x86_64-linux-gnu/cmake/mimalloc-2.0/mimalloc-none.cmake
#./debian/tmp/usr/lib/x86_64-linux-gnu/cmake/mimalloc-2.0/mimalloc-config.cmake
#./debian/tmp/usr/lib/x86_64-linux-gnu/cmake/mimalloc-2.0/mimalloc-config-version.cmake
